### ISSUE TITLE
OpenCage blog post

### ISSUE THREAD

**Issue by freyfogle** [tech2etc/Track-phone-number-location-using-python#1]
Ed fro OpenCage here. 

OpenCage can not be used to determine the location of a phone just based on phone number. 
Please see [our blog post about this](https://blog.opencagedata.com/post/we-can-not-convert-a-phone-number-into-a-location-sorry).

Please can you clarify this in the README (happy to submit a pull request if you like)?
Many people believe this service can track a phone just based on number, which is just not true.

**Comment by tech2etc** [comment]
Hey Ed!Thanks for the clear post. I have edited the readme file. Kindly check again and let me know if it's clear.Thanks.
      
        
        
          On Dec 28 2022, at 11:17 pm, Ed Freyfogle ***@***.***> wrote:
          
        
        
          
Ed fro OpenCage here.
OpenCage can not be used to determine the location of a phone just based on phone number.
Please see our blog post about this.
Please can you clarify this in the README (happy to submit a pull request if you like)?
Many people believe this service can track a phone just based on number, which is just not true.

**Comment by freyfogle** [comment]
thanks
